version=1

# Verzeichnisse, die vom Linting ausgeschlossen werden sollen
[[annotations]]
path = [
    "DerivedData/**",
    ".swiftpm/**",
    "build/**",
    ".build/**",
    "**/*.xcuserdatad/**",
    "**/*.xcscmblueprint/**",
    "**/*.xccheckout/**",
    ".DS_Store",
    "Tests/wcTests/benchmark/**",
]
ignore = true

[[annotations]]
path = "SOSutils.png"
precedence = "closest"
SPDX-FileCopyrightText = "© 2026 Sebastian Ritter"
SPDX-License-Identifier = "0BSD OR Apache-2.0 OR EUPL-1.2"

[[annotations]]
path = "Sources/core/Documentation.docc/**"
precedence = "closest"
SPDX-FileCopyrightText = "© 2026 Sebastian Ritter"
SPDX-License-Identifier = "0BSD OR Apache-2.0 OR EUPL-1.2"

[[annotations]]
path = "Sources/**/Documentation.docc/**"
precedence = "closest"
SPDX-FileCopyrightText = "© 2026 Sebastian Ritter"
SPDX-License-Identifier = "0BSD OR Apache-2.0 OR EUPL-1.2"

[[annotations]]
path = "Package.resolved"
precedence = "closest"
SPDX-FileCopyrightText = "© 2026 Sebastian Ritter"
SPDX-License-Identifier = "0BSD OR Apache-2.0 OR EUPL-1.2"
